version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: bookmark-postgres
    restart: always
    ports:
      - "5434:5432"           # Host:Container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: bookmarkapi
    networks:
      - bookmarkapi
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: bookmark-pgadmin
    restart: always
    ports:
      - "8081:80"              # Access pgAdmin at http://localhost:8081
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - bookmarkapi

volumes:
  pgdata:

networks:
  bookmarkapi:
